### PR TITLE
[Feature] Create initial meta structure for Movement

### PR DESCRIPTION
**Pull request by mmeldo**
See https://gist.github.com/mmeldo/038c757688f55251f73d90bdf73137ff

### CODE REVIEW

**Comment by mmeldo** [comment]
Coding is done, what this needs now is proper testing.

**Comment by mmeldo** [comment]
I understand if you do not have time, but I really would like to get it out there so people can try it and I can polish it so there will be no big issues. If you could add my friend who is helping me testing this as a collaborator so he can review and then merge, that would be fine. And if there is a problem, we can revert any time.

**Comment by mmeldo** [comment]
I got feedback from Anton that he finished with his testing and it looks fine. Thus if you did not find anything that would prevent from pushing this out, I believe we can go ahead. 
But when you will be doing the merge, please make sure that:
1. You will do "Squash and merge"
2. Name of the commit is "[Feature] Create initial meta structure for Movement", and not "Initial implementation" which is name of first commit, but it is not fitting for the final commit to master

**Review by J0eJames — APPROVED** [review]
With the additional ability to manually take control of a deed (for those rare, but possible situations), this looks great.  Did some testing, everything seemed to work as intended.

**Pull request merged**
